[project]
name = "Yelp-Review-Transformer"
version = "0.1.1"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
]
authors = [
    { name = "Ben Funk", email = "funkbj1@gmail.com" },
]
